from . import hr_employees
from . import hr_department
from . import hr_job
from . import hr_project
from . import hr_contract
from . import hr_payslip
from . import hr_calendar
from . import hr_leave
from . import hr_leave_type
from . import hr_attendance